// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

use crate::http::{HttpClient, Method, Request, RequestParts, encode_path};
use crate::pagination::Paginator;
use crate::types;

/// The `groups` methods.
#[derive(Clone, Debug)]
pub struct GroupsResource {
    http: HttpClient,
}

impl GroupsResource {
    pub(crate) fn new(http: HttpClient) -> Self {
        Self { http }
    }

    /// List groups
    ///
    /// Every group of the account, read live from WhatsApp.
    ///
    /// `GET /v1/accounts/{accountId}/groups`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn list(
        &self,
        account_id: &str,
        params: types::GroupsListParams,
    ) -> Paginator<types::GroupList> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups", encode_path(account_id)))
            .query_opt("limit", params.limit.as_ref())
            .retryable();
        Paginator::new(self.http.clone(), parts, "cursor", params.cursor)
    }

    /// Create a group or community
    ///
    /// With `community: true`, creates a community (`participants` may be empty); link groups to it with `POST .../groups/{groupId}/subgroups`.
    ///
    /// `POST /v1/accounts/{accountId}/groups`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn create(
        &self,
        account_id: &str,
        params: types::GroupsCreateParams,
    ) -> Request<types::Group> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups", encode_path(account_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Join a group by invite
    ///
    /// Join with an invite code or link.
    ///
    /// `POST /v1/accounts/{accountId}/groups/join`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn join(
        &self,
        account_id: &str,
        params: types::GroupsJoinParams,
    ) -> Request<types::GroupJoin> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/join", encode_path(account_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Preview a group invite
    ///
    /// The group behind an invite code, without joining.
    ///
    /// `GET /v1/accounts/{accountId}/groups/invites/{code}`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn get_invite(&self, account_id: &str, code: &str) -> Request<types::Group> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups/invites/{}", encode_path(account_id), encode_path(code)))
            .retryable();
        self.http.request(parts)
    }

    /// Get a group
    ///
    /// The group and its participants, read live from WhatsApp.
    ///
    /// `GET /v1/accounts/{accountId}/groups/{groupId}`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn get(&self, account_id: &str, group_id: &str) -> Request<types::Group> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups/{}", encode_path(account_id), encode_path(group_id)))
            .retryable();
        self.http.request(parts)
    }

    /// Update a group
    ///
    /// Change the name, description or settings. Admins only.
    ///
    /// `PATCH /v1/accounts/{accountId}/groups/{groupId}`
    ///
    /// Not idempotent: retried only when the request never reached the API or was refused with `429`.
    pub fn update(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsUpdateParams,
    ) -> Request<types::Group> {
        let parts = RequestParts::new(Method::Patch, format!("/v1/accounts/{}/groups/{}", encode_path(account_id), encode_path(group_id)))
            .body(&params);
        self.http.request(parts)
    }

    /// Leave a group
    ///
    /// The account leaves the group.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/leave`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn leave(&self, account_id: &str, group_id: &str) -> Request<()> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/leave", encode_path(account_id), encode_path(group_id)))
            .keyed()
            .no_content();
        self.http.request(parts)
    }

    /// Add participants
    ///
    /// Add contacts to the group. A contact whose privacy forbids it gets an `inviteCode` instead. Each contact gets its own result.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/participants/add`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn add_participants(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsAddParticipantsParams,
    ) -> Request<types::ParticipantResultList> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/participants/add", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Remove participants
    ///
    /// Remove contacts from the group. Each contact gets its own result.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/participants/remove`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn remove_participants(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsRemoveParticipantsParams,
    ) -> Request<types::ParticipantResultList> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/participants/remove", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Promote participants
    ///
    /// Make participants admins. Each contact gets its own result.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/participants/promote`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn promote_participants(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsPromoteParticipantsParams,
    ) -> Request<types::ParticipantResultList> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/participants/promote", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Demote participants
    ///
    /// Make admins regular participants. Each contact gets its own result.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/participants/demote`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn demote_participants(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsDemoteParticipantsParams,
    ) -> Request<types::ParticipantResultList> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/participants/demote", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Get the invite link
    ///
    /// The group's current invite link. Admins only.
    ///
    /// `GET /v1/accounts/{accountId}/groups/{groupId}/invite-link`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn get_invite_link(
        &self,
        account_id: &str,
        group_id: &str,
    ) -> Request<types::GroupInviteLink> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups/{}/invite-link", encode_path(account_id), encode_path(group_id)))
            .retryable();
        self.http.request(parts)
    }

    /// Reset the invite link
    ///
    /// Revoke the current invite link and return a new one. Admins only.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/invite-link/reset`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn reset_invite_link(
        &self,
        account_id: &str,
        group_id: &str,
    ) -> Request<types::GroupInviteLink> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/invite-link/reset", encode_path(account_id), encode_path(group_id)))
            .keyed();
        self.http.request(parts)
    }

    /// Set a group's picture
    ///
    /// JPEG. Admins only.
    ///
    /// `PUT /v1/accounts/{accountId}/groups/{groupId}/picture`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn set_picture(
        &self,
        account_id: &str,
        group_id: &str,
        params: impl Into<types::GroupsSetPictureParams>,
    ) -> Request<types::Picture> {
        let params = params.into();
        let parts = RequestParts::new(Method::Put, format!("/v1/accounts/{}/groups/{}/picture", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .retryable();
        self.http.request(parts)
    }

    /// Delete a group's picture
    ///
    /// Admins only.
    ///
    /// `DELETE /v1/accounts/{accountId}/groups/{groupId}/picture`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn delete_picture(&self, account_id: &str, group_id: &str) -> Request<()> {
        let parts = RequestParts::new(Method::Delete, format!("/v1/accounts/{}/groups/{}/picture", encode_path(account_id), encode_path(group_id)))
            .retryable()
            .no_content();
        self.http.request(parts)
    }

    /// List join requests
    ///
    /// Pending requests to join the group. Admins only.
    ///
    /// `GET /v1/accounts/{accountId}/groups/{groupId}/join-requests`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn list_join_requests(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsListJoinRequestsParams,
    ) -> Paginator<types::GroupJoinRequestList> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups/{}/join-requests", encode_path(account_id), encode_path(group_id)))
            .query_opt("limit", params.limit.as_ref())
            .retryable();
        Paginator::new(self.http.clone(), parts, "cursor", params.cursor)
    }

    /// Approve join requests
    ///
    /// Approve pending requests. Admins only. Each contact gets its own result.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/join-requests/approve`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn approve_join_requests(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsApproveJoinRequestsParams,
    ) -> Request<types::ParticipantResultList> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/join-requests/approve", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// Reject join requests
    ///
    /// Reject pending requests. Admins only. Each contact gets its own result.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/join-requests/reject`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn reject_join_requests(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsRejectJoinRequestsParams,
    ) -> Request<types::ParticipantResultList> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/join-requests/reject", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed();
        self.http.request(parts)
    }

    /// List a community's groups
    ///
    /// Groups linked to the community.
    ///
    /// `GET /v1/accounts/{accountId}/groups/{groupId}/subgroups`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn list_subgroups(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsListSubgroupsParams,
    ) -> Paginator<types::SubgroupList> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups/{}/subgroups", encode_path(account_id), encode_path(group_id)))
            .query_opt("limit", params.limit.as_ref())
            .retryable();
        Paginator::new(self.http.clone(), parts, "cursor", params.cursor)
    }

    /// Link a group to a community
    ///
    /// Admins of both only.
    ///
    /// `POST /v1/accounts/{accountId}/groups/{groupId}/subgroups`
    ///
    /// Sends `Idempotency-Key` (a random key, or your own with `.idempotency_key(..)`), so it is retried on timeouts, network errors, `429` and `5xx` without repeating its effect.
    pub fn link_subgroup(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsLinkSubgroupParams,
    ) -> Request<()> {
        let parts = RequestParts::new(Method::Post, format!("/v1/accounts/{}/groups/{}/subgroups", encode_path(account_id), encode_path(group_id)))
            .body(&params)
            .keyed()
            .no_content();
        self.http.request(parts)
    }

    /// Unlink a group from a community
    ///
    /// Admins only.
    ///
    /// `DELETE /v1/accounts/{accountId}/groups/{groupId}/subgroups/{subgroupId}`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn unlink_subgroup(
        &self,
        account_id: &str,
        group_id: &str,
        subgroup_id: &str,
    ) -> Request<()> {
        let parts = RequestParts::new(Method::Delete, format!("/v1/accounts/{}/groups/{}/subgroups/{}", encode_path(account_id), encode_path(group_id), encode_path(subgroup_id)))
            .retryable()
            .no_content();
        self.http.request(parts)
    }

    /// List a community's members
    ///
    /// Members across the community's linked groups.
    ///
    /// `GET /v1/accounts/{accountId}/groups/{groupId}/community-participants`
    ///
    /// Safe to repeat: retried on timeouts, network errors, `429` and `5xx`.
    pub fn list_community_participants(
        &self,
        account_id: &str,
        group_id: &str,
        params: types::GroupsListCommunityParticipantsParams,
    ) -> Paginator<types::CommunityParticipantList> {
        let parts = RequestParts::new(Method::Get, format!("/v1/accounts/{}/groups/{}/community-participants", encode_path(account_id), encode_path(group_id)))
            .query_opt("limit", params.limit.as_ref())
            .retryable();
        Paginator::new(self.http.clone(), parts, "cursor", params.cursor)
    }
}
