// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

//! One module per resource of the API.

pub mod accounts;
pub mod bots;
pub mod branding;
pub mod calls;
pub mod channels;
pub mod chats;
pub mod contacts;
pub mod groups;
pub mod invitations;
pub mod labels;
pub mod messages;
pub mod orders;
pub mod privacy;
pub mod profile;
pub mod projects;
pub mod proxy_locations;
pub mod sticker_packs;
pub mod stories;
pub mod usage;
pub mod webhook_endpoints;
