// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

//! Request and response tests against a local mock server. Nothing here
//! calls the live API.

use wuapi as sdk;

#[rustfmt::skip]
mod generated;
mod runtime;
mod support;
mod webhook;

#[test]
fn constants_match_the_manifest() {
    assert_eq!(sdk::VERSION, env!("CARGO_PKG_VERSION"));
    assert_eq!(sdk::PACKAGE_NAME, env!("CARGO_PKG_NAME"));
    let agent = concat!(env!("CARGO_PKG_NAME"), "-rust/", env!("CARGO_PKG_VERSION"));
    assert_eq!(sdk::USER_AGENT, agent);
}
