// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

#![doc = include_str!("../README.md")]
#![forbid(unsafe_code)]

#[rustfmt::skip]
pub mod client;
pub mod error;
pub mod http;
mod macros;
#[rustfmt::skip]
pub mod meta;
pub mod pagination;
#[rustfmt::skip]
pub mod resources;
mod serde_helpers;
#[rustfmt::skip]
pub mod types;
pub mod webhook;

pub use client::Wuapi;
pub use error::{Error, WebhookVerificationError};
pub use http::{ClientBuilder, HttpClient, Method, Request, RequestParts, RetryPolicy};
pub use http::{encode_path, random_key};
pub use meta::{API_KEY_ENV, DEFAULT_BASE_URL, IDEMPOTENCY_HEADER, PROJECT_HEADER};
pub use meta::{PACKAGE_NAME, USER_AGENT, VERSION};
pub use pagination::{CursorPage, Paginator};
pub use webhook::verify_webhook_with_tolerance;
pub use webhook::{compute_signature, verify_signature, verify_webhook};

/// The client, under the name every SDK built by this generator shares: an
/// alias of [`Wuapi`].
pub type Client = Wuapi;
