// Generated by wuapi-codegen from the OpenAPI spec. Do not edit: run `bun run codegen`.

//! Constants of this crate and of the API.

/// The version of this crate.
pub const VERSION: &str = "0.11.0";
/// The name of this crate.
pub const PACKAGE_NAME: &str = "wuapi";
/// The API's production URL.
pub const DEFAULT_BASE_URL: &str = "https://api.wuapi.dev";
/// Environment variable the API key is read from.
pub const API_KEY_ENV: &str = "WUAPI_API_KEY";
/// Header that scopes a request to a project.
pub const PROJECT_HEADER: &str = "Wuapi-Project";
/// Header that makes a request safe to retry.
pub const IDEMPOTENCY_HEADER: &str = "Idempotency-Key";
/// The `User-Agent` this crate sends.
pub const USER_AGENT: &str = "wuapi-rust/0.11.0";
